### ISSUE TITLE
kills the alaya during the fast sync and restart alaya, alaya panic

### ISSUE THREAD

**Issue by sigrlot** [AlayaNetwork/Alaya-Go#124]
kills the alaya during the fast sync, and start again by fast, alaya raise an error, after changing sync mode to full, it still raise error

== log ================

panic: base num 25492001 can't be greater than currentHead Number 233472

goroutine 1 [running]:
github.com/AlayaNetwork/Alaya-Go/core/snapshotdb.Instance(0x0, 0x0)
 /opt/jenkins/workspace/Alaya/build_ubuntu/core/snapshotdb/snapshotdb.go:199 +0x2e7
github.com/AlayaNetwork/Alaya-Go/x/gov.get(0x1a2e75e6ed7f78fb, 0x4540c16f2c5dd85a, 0x246dd8695ebe5947, 0x19d43bc222acce25, 0xc00014ef90, 0x21, 0x21, 0x21, 0x21, 0x21ba460, ...)
 /opt/jenkins/workspace/Alaya/build_ubuntu/x/gov/gov_snapdb.go:30 +0x26
github.com/AlayaNetwork/Alaya-Go/x/gov.findGovernParamValue(0x15f09a1, 0x5, 0x1604627, 0x10, 0x1a2e75e6ed7f78fb, 0x4540c16f2c5dd85a, 0x246dd8695ebe5947, 0x19d43bc222acce25, 0x8, 0xc000000300, ...)
 /opt/jenkins/workspace/Alaya/build_ubuntu/x/gov/gov_snapdb.go:256 +0x1a5
github.com/AlayaNetwork/Alaya-Go/x/gov.GetGovernParamValue(0x15f09a1, 0x5, 0x1604627, 0x10, 0x0, 0x1a2e75e6ed7f78fb, 0x4540c16f2c5dd85a, 0x246dd8695ebe5947, 0x19d43bc222acce25, 0x246dd8695ebe5947, ...)
 /opt/jenkins/workspace/Alaya/build_ubuntu/x/gov/gov.go:690 +0x85
github.com/AlayaNetwork/Alaya-Go/x/gov.GovernMaxBlockGasLimit(0x0, 0x1a2e75e6ed7f78fb, 0x4540c16f2c5dd85a, 0x246dd8695ebe5947, 0x19d43bc222acce25, 0x2f, 0x34630b8a000, 0xa)
 /opt/jenkins/workspace/Alaya/build_ubuntu/x/gov/gov.go:820 +0x73
github.com/AlayaNetwork/Alaya-Go/eth.New(0xc0000d8a00, 0xc000241500, 0x30, 0x157f860, 0xc0002e58f0)
 /opt/jenkins/workspace/Alaya/build_ubuntu/eth/backend.go:294 +0xf45
github.com/AlayaNetwork/Alaya-Go/cmd/utils.RegisterEthService.func2(0xc0000d8a00, 0xc0002acd50, 0xc0002e5a70, 0xc0000b83e0, 0x2)
 /opt/jenkins/workspace/Alaya/build_ubuntu/cmd/utils/flags.go:1198 +0x46
github.com/AlayaNetwork/Alaya-Go/node.(*Node).Start(0xc000091400, 0x0, 0x0)
 /opt/jenkins/workspace/Alaya/build_ubuntu/node/node.go:228 +0x443
github.com/AlayaNetwork/Alaya-Go/cmd/utils.StartNode(0xc000091400)
 /opt/jenkins/workspace/Alaya/build_ubuntu/cmd/utils/cmd.go:67 +0x2f
main.startNode(0xc00003c420, 0xc000091400)
 /opt/jenkins/workspace/Alaya/build_ubuntu/cmd/alaya/main.go:308 +0x6a
main.pla

**Comment by benbaley** [comment]
fixed in #125
