### ISSUE TITLE
Setting needs to estimate the gas, the amount is sufficient, report an error "out of gas"

### ISSUE THREAD

**Issue by pengzhepz** [AlayaNetwork/Alaya-Go#126]
Setting needs to estimate the gas, the amount is sufficient, report an error "out of gas"

Alaya version: alaya version 0.16.1
OS & Version: Windows/Linux/OSX

**Comment by pengzhepz** [comment]
Please see the attachment for the log 
[platon.log](https://github.com/AlayaNetwork/Alaya-Go/files/7081910/platon.log)

**Comment by benbaley** [comment]
fixed in #125
