### ISSUE TITLE
0x地址发起锁仓交易，返回logs里面的地址是bech32地址

### ISSUE THREAD

**Issue by pengzhepz** [AlayaNetwork/Alaya-Go#130]
0x地址发起锁仓交易，返回logs里面的地址是bech32地址

![d5009266a0118ba0ab3f1a5933e758d](https://user-images.githubusercontent.com/78134846/131991367-e74d0b85-311e-4876-aa1c-d51e9c00b655.png)

**Comment by pengzhepz** [comment]
以太坊合约也有同样问题，0x发起交易，但是事件返回的还是atp地址
![image](https://user-images.githubusercontent.com/78134846/132159062-a6caa3b1-3300-4acf-beb4-58c13703bc56.png)

**Comment by benbaley** [comment]
fixed in #131
