### ISSUE TITLE
Use the parameter --rpc.gascap to set the upper limit of estimated gas. If the setting is exceeded, the success can still be estimated 

### ISSUE THREAD

**Issue by pengzhepz** [AlayaNetwork/Alaya-Go#133]
Use the parameter --rpc.gascap to set the upper limit of estimated gas. If the setting is exceeded, the success can still be estimated 

Alaya version: `alaya version`   0.16.1
OS & Version: Windows/Linux/OSX

**Comment by benbaley** [comment]
fixed in #131
