### ISSUE TITLE
节点启动参数指定冷冻数据库存储地址，拷贝原数据库到指定地址后重启失败

### ISSUE THREAD

**Issue by pengzhepz** [AlayaNetwork/Alaya-Go#138]
#### System information

Alaya version: `alaya version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Expected behaviour
1、预期重启成功，数据会存储到指定的冷冻数据库中。

#### Actual behaviour

1、实际启动失败，报错Fatal: Error starting protocol stack: needRewind due to data error,please clean your data

#### Steps to reproduce the behaviour

1、启动一个节点，不指定冷冻数据库地址，fast/full同步
2、kill掉
3、copy 默认冷冻数据库到指定目录
4、启动参数添加--datadir.ancient 启动节点

**Comment by benbaley** [comment]
fixed in #137
