### ISSUE TITLE
Use the parameter --rpc.gascap to set the upper limit of the estimated gas. If the setting is too low, call the platon_call method and report an error "err: intrinsic gas too low (supplied gas 21000)" 

### ISSUE THREAD

**Issue by pengzhepz** [AlayaNetwork/Alaya-Go#139]
Use the parameter --rpc.gascap to set the upper limit of the estimated gas. If the setting is too low, call the platon_call method and report an error "err: intrinsic gas too low (supplied gas 21000)" 

![image](https://user-images.githubusercontent.com/78134846/132670419-7a78a46e-4373-4863-b07a-3d0448796df4.png)

**Comment by benbaley** [comment]
设计如此，防ddos攻击的
