### ISSUE TITLE
wasm 的 platon_block_hash 函数获取指定高度区块的区块hash，升级前后获取的区块hash不一样造成版本升级后无法同步区块。

### ISSUE THREAD

**Issue by jatel** [AlayaNetwork/Alaya-Go#18]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

#### System information

Alaya version: `alaya version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Expected behaviour

版本升级后可以正常同步。

#### Actual behaviour

升级后的代码获取当前块高 256 个区块之前的区块 hash 为 0，而升级之前的代码可以获取区块 hash。

#### Steps to reproduce the behaviour

在 wasm 智能合约里通过 platon_block_hash  获取 256 个区块之前的区块 hash
将 区块 hash 存入合约的状态数据中

#### Backtrace

````
[backtrace]
````

**Comment by benbaley** [comment]
fixed in #19
