### ISSUE TITLE
选举共识节点的随机性不够

### ISSUE THREAD

**Issue by WeiLoy** [AlayaNetwork/Alaya-Go#25]
Alaya在共识机制中关于每个共识轮共识节点选取的设计原则是：

1. 足够的随机，通过VRF确保每一轮的选举结果都不可预测
2. 公平性，节点自身的权益比重占总权益比重越高，节点被选中的概率相对越大
3. 抑制权力集中，高权重不一定会获得高收益，权重的平方根占所有节点权重平方根的和的比，与节点累积被选中次数占总选举次数的比， 趋近于相同

在目前的实现上，从长期运行结果来看，备选节点被选为共识节点的概率偏向于权重高的前部节点，逐渐趋向于中心化了。

#### System information

Alaya version: `v0.15.0`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Expected behaviour

1. 足够的随机，通过VRF确保每一轮的选举结果都不可预测
2. 公平性，节点自身的权益比重占总权益比重越高，节点被选中的概率相对越大
3. 抑制权力集中，高权重不一定会获得高收益，权重的平方根占所有节点权重平方根的和的比，与节点累积被选中次数占总选举次数的比， 趋近于相同

#### Actual behaviour

选中为共识节点的趋势偏向于排名前部的高权重备选节点

#### Steps to reproduce the behaviour

https://scan.alaya.network/node

**Comment by WeiLoy** [comment]
## 优化方案
针对目前随机性的优化，一种可行的方案是，在选举的算法中再引入一个独立的具有随机性的机制，并且调整二项分布的期望值，保证选举的结果更加去中心化。

现有的选举机制为：每个节点使用不同的VRF随机数，从各自的二项分布累积分布曲线上获取一个随机数x，将所有x逆序排列，选取前f个节点为共识节点，当出现x值相同时，按质押块高正序排列，所以有一定的可能性会影响相邻节点间的随机性。
优化后的选举机制：抽取出每个节点的随机数x值后，在相同的情况下，使用shuffle算法随机排列，保证选举的过程完全随机避免可能出现固定的排序规律。

![alaya权重](https://user-images.githubusercontent.com/19259075/121991078-85b4a700-cdd1-11eb-9e21-d6e54f2b7859.png)
> 备选节点的权重排名

### 测试方式
&nbsp;&nbsp;&nbsp;&nbsp;先从101个备选节点中挑出前25个作为当前共识节点列表，随后用剩余的76个节点选举，选举出8个节点，追加到当前共识节点列表，并且移出前8个节点放入到备选节点中，再用76个备选节点选举，重复此过程
### 测试次数
&nbsp;&nbsp;&nbsp;&nbsp;25W
### 测试数据
&nbsp;&nbsp;&nbsp;&nbsp;alaya权重
### 期望值
&nbsp;&nbsp;&nbsp;&nbsp;20、24、25、36、30、33

### 测试结果
![alaya不同期望值对比](https://user-images.githubusercontent.com/19259075/121991769-ec869000-cdd2-11eb-8631-143fae8e58eb.png)
> X轴：备选节点按权重高低的排列
> Y轴：节点选中次数占总选中次数比例和节点权重占总权重比例的比
> 线：不同期望值选举结果

![alaya期望值_20_25_33对比](https://user-images.githubusercontent.com/19259075/121991978-48511900-cdd3-11eb-8e47-70d01602b77a.png)

从结果中表明，将期望值设定为`25`较符合预期。

**Comment by WeiLoy** [comment]
fix #36

**Comment by junjiequ123** [comment]
Randomness of validator election is NOT enough, causing unfairness

-- where is the english article regarding this fix?  please add a link here
-- original design please refer to https://medium.com/platon-network/technology-platon-a-randomized-scheme-for-validator-election-in-the-pos-consensus-2-cff3fca47cee
