### ISSUE TITLE
新增查询共识周期、结算周期、备选节点候选人列表api接口

### ISSUE THREAD

**Issue by niuxiaojie81** [AlayaNetwork/Alaya-Go#295]
目前查询需要调用类似`platon.call({to: "atp1zqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqzfyslg3", data:"0xc48382044c"})`的接口返回16进制字符串，再通过 rlpdump 工具解析，操作太过繁琐，且当列表过长的情况下，rlpdump 工具无法解析。
希望能在debug模块下开发直接返回列表明文的接口

**Comment by WeiLoy** [comment]
实现于[#299 ]
