### ISSUE TITLE
节点解质押失败

### ISSUE THREAD

**Issue by HiZhaoYun** [AlayaNetwork/Alaya-Go#46]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

#### System information

Alaya version: `alaya version` 0.15.0
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

失败了，节点是候选中状态，返回错误好像是一个网页

Invalid response received: 502; <html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.14.0 (Ubuntu)</center>
</body>
</html>

**Comment by benbaley** [comment]
请问这个是使用mtool操作的吗？ 请tiissue到这里哦 https://github.com/AlayaNetwork/mtool/issues
