### ISSUE TITLE
新建节点出现问题

### ISSUE THREAD

**Issue by HiZhaoYun** [AlayaNetwork/Alaya-Go#60]
按照教程一步一步来的。

`ERROR[08-07|18:09:27.992] ReadMsg from peer error, connection is closed
ERROR[08-07|18:09:27.992] ReadMsg from peer error, connection is closed
ERROR[08-07|18:09:27.992] Read peer message error                  id=a6bbf49d6f1df8e3 conn=inbound err=EOF
ERROR[08-07|18:09:27.992] CBFT message handling failed             id=a6bbf49d6f1df8e3 conn=inbound peerID=a6bbf49d6f1df8e3 err=EOF
ERROR[08-07|18:09:27.992] read peer message error                  id=a6bbf49d6f1df8e3 conn=inbound err=EOF
ERROR[08-07|18:09:27.992] PlatON message handling failed           id=a6bbf49d6f1df8e3 conn=inbound err=EOF
ERROR[08-07|18:10:04.036] Low version of p2p protocol version      id=ef47103ceb8d8794 addr=47.244.22.16:25796 conn=inbound err=ef47103ceb8d8794
ERROR[08-07|18:10:06.056] ReadMsg error1                           err="read tcp 172.21.41.151:16789->150.158.156.92:55620: read: connection reset by peer"
ERROR[08-07|18:10:06.056] ReadMsg from peer error, connection is closed
ERROR[08-07|18:10:06.056] ReadMsg from peer error, connection is closed
ERROR[08-07|18:10:06.056] Read peer message error                  id=a6bbf49d6f1df8e3 conn=inbound err=EOF
ERROR[08-07|18:10:06.056] CBFT message handling failed             id=a6bbf49d6f1df8e3 conn=inbound peerID=a6bbf49d6f1df8e3 err=EOF
ERROR[08-07|18:10:06.056] read peer message error                  id=a6bbf49d6f1df8e3 conn=inbound err=EOF
ERROR[08-07|18:10:06.056] PlatON message handling failed           id=a6bbf49d6f1df8e3 conn=inbound err=EOF
ERROR[08-07|18:10:08.284] ReadMsg error3                           err="read tcp 172.21.41.151:16789->34.93.140.105:36170: read: connection reset by peer"
ERROR[08-07|18:10:14.788] ReadMsg error2                           err="read tcp 172.21.41.151:16789->35.240.150.63:23412: read: connection reset by peer"`

**Comment by HiZhaoYun** [comment]
阿里云服务器

**Comment by benbaley** [comment]
出现这些ERROR日志并不能说明节点有问题，可能是本地或对端节点不稳定导致的P2P消息异常
请用netstat命令检查一下p2p端口，看是否已经建立了tcp连接？

**Comment by junjiequ123** [comment]
ReadMsg from peer error, connection is closed when setup new node

--- add english translation to prevent submition of duplicated issues, and be search friendly

**Comment by HiZhaoYun** [comment]
![image](https://user-images.githubusercontent.com/59190880/128722314-ebdf6606-65f7-429c-82ea-0824eeeb7d5a.png)
@benbaley ,检查了一下我也看不出来是否正常,为了测试新建的阿里云节点

**Comment by HiZhaoYun** [comment]
依旧是一样的错误

**Comment by benbaley** [comment]
你这个是Alaya主网吗？ 请在阿里云服务器上检查16789端口是否开放了UDP协议， 另外请在控制台使用`platon.getBlock(0).hash`查看一下hash值， 输出的是以下的值才是对的
```
> platon.getBlock(0).hash
"0xfb787fede6752e1a5ad85d2c6fc140454759be5e69d86d2425ceac22c23bd419"
```

**Comment by HiZhaoYun** [comment]
@benbaley 哈希值是对的，我是按照文档来的，是否是因为文档上是0.16.0，但是主网节点还不是这个版本，所以节点间通信失败？

**Comment by benbaley** [comment]
如果服务器是国内片区的， 可能会因为墙的原因连不上外部节点， 您可以试着手动添加一些节点看看，比如：
```
addPeer("enode://"01732a1a8dfaee8cfd2916bbdf93798ad316b5b3b96f686dcc35ee3415a8b0c423b1d897d977f3739132231c82ee0fe49c0f506c378b5db45260d31b1cdeb178@47.254.125.14:16789")
addPeer("enode://"069ee839ad45933a2dd05ee9c26e3783f66313344600b26d8976ffef156ee1472f4a42a85791138484ff1ca675ab70d45cf7dabe4f42777ae7e7cf8d1e60deea@119.8.188.159:16789")
addPeer("enode://"168fff55f6a28c3f10802e90cefb4daf58eb9a60c55eaaeda6588b20eece884ab9104da866633929e3c0ea413de2624b361939cf1513e1b67460686b7192f528@47.254.239.159:16789")
addPeer("enode://"19b8fb478a8502a25e461270122ece3135b15dc0de118264495bae30d39af81fd9134ed95364e6a39c3eebfba57fbffa7961a5158d3dac0f0da0313dac7af024@18.117.233.189:16789")
addPeer("enode://"2dcb6b2368ea69ece2cc71fda719e76ba63e20eaac290df752f4ac88ef7efac9ddaa6c7ed024888546462ca028b269247d05a39eeded148032a5e9288565f7de@34.129.220.62:16789")
addPeer("enode://"3ab721f2f51e2d572d18ef182ae05f54ce01360119f2669788b40f5f1338357345344716a1170874b469b11281c1e3cc8a7f31c88b07527cacb55c8b66ea05a0@34.101.129.242:16789")
addPeer("enode://"44c570fc738bcd25e7ce6becdeefeaa57d3d8e97ff84ba8ae4da43c4068888b413caeb78123a6cd41bb30dffb52ad3b9427d5ce27eb6b065bfbc11d310f6d779@35.186.153.142:16789")
addPeer("enode://"49648f184dab8acf0927238452e1f7e8f0e86135dcd148baa0a2d22cd931ed9770f726fccf13a3976bbdb738a880a074dc21d811037190267cd9c8c1378a6043@54.154.156.84:16789")
addPeer("enode://"5c0c3c22e8b7a8225f27c46aa4757effb0f67912d886033ab0f5cd2f4201490f7dd28adcf56b3ae0847005e7d6f394519e20da30d507f1c16b6595278de057e5@42.192.81.147:16789")
addPeer("enode://"6eeddc7bea67b08cb2bff68b4c5c6cda0b4234779a21b78b244203acab504b801ca299dcbf5b50c4650e502196b05f4fd6f3582fd0973528fd3047c36ab2198d@54.149.83.174:16789")
addPeer("enode://"70c598ebdd53b20482fba31876699193cbbd47b3dc5f0c687fcb5e7062a01b9e0862ecc65e3620634117a971b5cc6e8c0abcc125bc63274456d9d5b0c39ad72f@34.141.6.100:16789")
addPeer("enode://"7dc831a1668827507528992d72471a397dc0e8a65ade1a91ba197c76a89ed7336eb05bf098fc11083648ad48b2b0f6d4903cc17be221115316112b81ba72d427@34.129.56.131:16789")
addPeer("enode://"80d92c92a0f97c48edcb6e35d66302a43a54323955a4f2d6ce6d641533e42b7497e9a59c32adee84293152cac35608164325395d4fe0050a737e8d6e1026c8b3@34.107.115.32:16789")
addPeer("enode://"85fd7813f1872885722929c1ee41c7046aa938fc4b158935032d1a14aa129cabc008dc3e1b8aceb5f500b58256867b2d59f0f97d42215b0ec9f5ed2ffc3642ed@34.126.148.31:16789")
addPeer("enode://"b6cb09bf53ca3133b932f1a5cb473ef7ddc67925bc4579891c85bce88a564135ecafb9619c9170f9acc5aa304c1e65389437cf06f74c4bae88a580c7e4a5d05e@34.129.125.179:16789")
addPeer("enode://"bc93ef4c138c4e010a57ba7c4565faaf07f5cdbe4bff58f92f7aa3e9a10e830dcb4a6f63fe04e61872c5ea1f98a302cfb6cb0004538db0cf3c7c8d697dc5bfee@35.183.248.205:16789")
addPeer("enode://"efbd089457980cb916e6cd196591c673720882930f30a2bd0c11c1a86478c47bd719ad565de36f717989c9722ba5aa98534062daa300cb66ef6469cf52e2a955@35.244.9.141:16789")
addPeer("enode://"fad2c7f917eb3057d85031eae8bbda52541b527dd1d24a25e7e9b40d7329570a85dc45ec61b189a9cc30047ae906a08dc375558828e1c76dc853ce99b42b91e4@167.99.107.253:16789")
addPeer("enode://"faebd43ae2be00cf6a2a8ebe68ef6cbe8a075b7cf7d1e5f99b9ee46c734f56c640fbf8f1eb611f08623d3b588ae8f6c837cfef1e91d3170ba3c398dfce0d47f2@195.201.10.227:16790")
addPeer("enode://"fb930daf27a779e7d678ca1a3ac5eb55885e00fd3bac1fb1ffd72d6ec36137ecfa89ffc26a71b68d3d578e917a10bcd8438e9bd4ee00c5ac9dfa96d1efec25c7@152.32.128.116:16789")
```

**Comment by HiZhaoYun** [comment]
你们自己有没有试过呀，按照文档是否能加入alaya主网,我注意到你们的文档好像跟以前不一样，以前我跑过节点都正常，操作步骤也一样，这次怎么都不行

**Comment by benbaley** [comment]
请问这个问题是否已经解决了？

**Comment by HiZhaoYun** [comment]
> 请问这个问题是否已经解决了？

没有的，我试了一下在腾讯云（海外区域）也不行，木有办法了 @benbaley

**Comment by HiZhaoYun** [comment]
你可以开一个临时的节点试一下

**Comment by benbaley** [comment]
请问这个问题后面有解决吗？

**Comment by benbaley** [comment]
Closed due to long time lack of feedback
