### ISSUE TITLE
迁移钱包后不能够使用

### ISSUE THREAD

**Issue by lzdohh** [AlayaNetwork/Alaya-Go#62]
#### System information

Alaya version: 0.16.0-unstable
OS & Version: Linux
Commit hash : c1221a425d6b6b0c916c2eecbf1f74ab5224291c

#### Expected behaviour
1、在0.16.0的节点上操作
alaya attach http://localhost:6789 -exec platon.accounts 能够展示迁移过来的钱包（该钱包使用0.16.0之前的版本创建的）

#### Actual behaviour
1、在0.16.0的节点上操作
alaya attach http://localhost:6789 -exec platon.accounts 不能够展示迁移过来的钱包

#### Steps to reproduce the behaviour
1、使用0.16.0之前的版本创建钱包，把该钱包复制到另一个节点（该节点使用0.16.0版本）使用
2、alaya attach http://localhost:6789 -exec platon.accounts查看不到钱包

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by niuxiaojie81** [comment]
在新版本的钱包文件中，去除了mainnet和testnet的区分，可以手动修改一下钱包文件，只保留mainnet地址
示例：
```
"address": {
		"mainnet": "atp1uqhygcm8djytd9fa58c64w7yuwelurat4uql49",
		"testnet": "atx1uqhygcm8djytd9fa58c64w7yuweluratl6u4x0"
	}
```
修改为

`"address": "atp1uqhygcm8djytd9fa58c64w7yuwelurat4uql49"`

**Comment by junjiequ123** [comment]
v0.16.0 doesn't recognize Wallets generated in previous version

-- add comments for english search to avoid submit duplicated issues

**Comment by benbaley** [comment]
因长时间未反馈， 该issue关闭， 如果问题依然存在或有新的重现条件， 请reopen该issue
